name: iris-flower-classifier
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  - pandas>=1.5,<3.0
  - scikit-learn==1.7.0
  - joblib
  - pip
  - pip:
      - streamlit
      - gdown
      - matplotlib
      - seaborn
